### ISSUE TITLE
Taxonomy Selector type Select error notices

### ISSUE THREAD

**Issue by dademaru** [mcaskill/acf-field-taxonomy-selector#2]
Hi,

while I confirm [issue #1](https://github.com/mcaskill/acf-field-taxonomy-selector/issues/1) is fixed,
I get the following error notices above your **ACF Taxonomy Selector** type **Select** while editing a post:

```Notice: Undefined index: ui in /advanced-custom-fields-pro/includes/fields/class-acf-field-select.php on line 280```

```Notice: Undefined index: ajax in /advanced-custom-fields-pro/includes/fields/class-acf-field-select.php on line 281```

```Notice: Undefined index: ui in /advanced-custom-fields-pro/includes/fields/class-acf-field-select.php on line 305```

**Appearance** => '**select**' may have been updated in ACF pro since your plugin last update.

Thanks,
Davide

**Comment by mcaskill** [comment]
@dademaru Hi! I apologize for the issues this field is causing. Unfortunately, I didn't have time to test the plugin after fixing that error. I'm unsure when I might have time to address this.

Are you willing to submit a PR for this issue and any other PHP warnings and errors you might encounter? Thanks!

**Comment by mcaskill** [comment]
Closing because I have not been able to manage this package.

I recommend [ACF Extended](https://acf-extended.com).
